[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Primary processing window - focused exactly on the observed processing time (13:07)
[[scheduled]]
  function = "process-daily-batch"
  # Run at minute 7 of the 1 PM hour (13:07) - exact start time
  schedule = "7 13 * * *"
  
  [scheduled.environment]
    IS_SCHEDULED = "true"

# Frequent checks for the 30 minutes after the expected processing time
[[scheduled]]
  function = "process-daily-batch"
  # Run every minute from 13:08 to 13:37 UTC
  # This covers the 30 minutes after the expected processing time
  schedule = "8-37 13 * * *"
  
  [scheduled.environment]
    IS_SCHEDULED = "true"
