[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Schedule the process-daily-batch function at incrementing times
# Day 1: 1:00 PM UTC (13:00)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "0 13 * * *"

# Day 2: 1:01 PM UTC (13:01)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "1 13 * * *"

# Day 3: 1:02 PM UTC (13:02)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "2 13 * * *"

# Day 4: 1:03 PM UTC (13:03)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "3 13 * * *"

# Day 5: 1:04 PM UTC (13:04)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "4 13 * * *"

# Day 6: 1:05 PM UTC (13:05)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "5 13 * * *"

# Day 7: 1:06 PM UTC (13:06)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "6 13 * * *"

# Day 8: 1:07 PM UTC (13:07)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "7 13 * * *"

# Day 9: 1:08 PM UTC (13:08)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "8 13 * * *"

# Day 10: 1:09 PM UTC (13:09)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "9 13 * * *"

# Day 11: 1:10 PM UTC (13:10)
[[scheduled]]
  function = "process-daily-batch"
  schedule = "10 13 * * *"
