[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Schedule to run every minute between 1:00-1:15 PM UTC daily
# The function will internally check if it's the right time to process based on the day
[[scheduled]]
  function = "process-daily-batch"
  # Run every minute from 1:00-1:15 PM UTC
  schedule = "0-15 13 * * *"
